name: rfml
dependencies:
  - python=3.11
  - pip
  - jupyter
  - matplotlib>=3.7.1
  - numpy>=1.25.2
  - pandas>=2.0.3
  - scikit-learn>=1.2.2
  - pip:
    - torch>=2.0.1
    - git+https://github.com/vtnsi/rfml_tuts.git
